import type { Recipe, RecipeLocale, RecipeTargetCardType } from "@/types";

/**
 * Build a self-contained HTML document for a Recipe.
 *
 * "Self-contained" means: inline CSS, optional inline base64 image, no external
 * resources. The resulting string can be saved as `.html` and opened anywhere
 * — including offline or attached to email — and still render correctly.
 */

const SECTION_ORDER: RecipeTargetCardType[] = [
  "outputs",
  "outcomes-short",
  "outcomes-intermediate",
];

// Document-level branding. Kept as a constant at the top of the file so it can
// be swapped out later without hunting through the template strings.
const DOCUMENT_TITLE = "MUSE RECIPE";

const labels = {
  en: {
    generatedAt: "Generated",
    metricsCount: (n: number) => `${n} metrics`,
    sectionOutputs: "Outputs",
    sectionShort: "Short-term Outcomes",
    sectionIntermediate: "Intermediate Outcomes",
    measurementSteps: "Measurement steps",
    dataCollectionMethod: "Data collection method",
    frequency: "Frequency",
    targetValue: "Target value",
    cautions: "Cautions",
    parentLabel: "From",
    none: "—",
    imageAlt: "Logic model diagram",
    poweredBy: "Generated by MUSE · muse.beaconlabs.io",
  },
  ja: {
    generatedAt: "生成日時",
    metricsCount: (n: number) => `${n} 件の指標`,
    sectionOutputs: "アウトプット",
    sectionShort: "短期アウトカム",
    sectionIntermediate: "中期アウトカム",
    measurementSteps: "測定手順",
    dataCollectionMethod: "データ収集方法",
    frequency: "頻度",
    targetValue: "目標値",
    cautions: "注意点",
    parentLabel: "対象カード",
    none: "—",
    imageAlt: "ロジックモデル図",
    poweredBy: "MUSE で生成 · muse.beaconlabs.io",
  },
} as const;

function sectionLabel(t: (typeof labels)[RecipeLocale], type: RecipeTargetCardType): string {
  switch (type) {
    case "outputs":
      return t.sectionOutputs;
    case "outcomes-short":
      return t.sectionShort;
    case "outcomes-intermediate":
      return t.sectionIntermediate;
  }
}

// Minimal HTML escape — covers the 5 characters that matter for attribute
// and text-content contexts. We never inject untrusted content into
// <script>/<style>/comment positions, so this is sufficient.
function htmlEscape(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderList(items: string[]): string {
  if (items.length === 0) return "";
  return `<ul>${items.map((v) => `<li>${htmlEscape(v)}</li>`).join("")}</ul>`;
}

function renderOrderedList(items: string[]): string {
  if (items.length === 0) return "";
  return `<ol>${items.map((v) => `<li>${htmlEscape(v)}</li>`).join("")}</ol>`;
}

function renderMetricCard(item: Recipe["items"][number], t: (typeof labels)[RecipeLocale]): string {
  return `
    <article class="metric-card">
      <h3>${htmlEscape(item.metricName)}</h3>
      <p class="parent">${htmlEscape(t.parentLabel)}: ${htmlEscape(item.parentCardTitle)}</p>

      <section class="field">
        <h4>${htmlEscape(t.measurementSteps)}</h4>
        ${renderOrderedList(item.measurementSteps)}
      </section>

      <section class="field">
        <h4>${htmlEscape(t.dataCollectionMethod)}</h4>
        <p>${htmlEscape(item.dataCollectionMethod)}</p>
      </section>

      <div class="inline-row">
        <div class="inline-cell">
          <h4>${htmlEscape(t.frequency)}</h4>
          <p>${htmlEscape(item.frequency)}</p>
        </div>
        <div class="inline-cell">
          <h4>${htmlEscape(t.targetValue)}</h4>
          <p>${item.targetValue ? htmlEscape(item.targetValue) : t.none}</p>
        </div>
      </div>

      ${
        item.cautions.length > 0
          ? `<section class="field cautions"><h4>${htmlEscape(t.cautions)}</h4>${renderList(item.cautions)}</section>`
          : ""
      }
    </article>
  `;
}

function renderSection(
  type: RecipeTargetCardType,
  items: Recipe["items"],
  t: (typeof labels)[RecipeLocale],
): string {
  if (items.length === 0) return "";
  return `
    <section class="metric-section" data-type="${type}">
      <h2>${htmlEscape(sectionLabel(t, type))}</h2>
      ${items.map((i) => renderMetricCard(i, t)).join("")}
    </section>
  `;
}

const CSS = `
  *, *::before, *::after { box-sizing: border-box; }
  html { font-size: 16px; }
  body {
    margin: 0;
    padding: 32px 24px 64px;
    background: #f8fafc;
    color: #1e293b;
    font-family: -apple-system, BlinkMacSystemFont, "Hiragino Sans", "Yu Gothic",
      "Noto Sans CJK JP", "Segoe UI", Roboto, sans-serif;
    line-height: 1.6;
  }
  .container { max-width: 880px; margin: 0 auto; }
  header.cover { margin-bottom: 32px; }
  header.cover h1 {
    font-size: 22px;
    line-height: 1.2;
    letter-spacing: 0.04em;
    margin: 0 0 4px;
    color: #0f172a;
  }
  header.cover .meta {
    margin: 0 0 16px;
    color: #64748b;
    font-size: 13px;
  }
  img.logic-model {
    display: block;
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    border: 1px solid #e2e8f0;
    background: #fff;
    box-shadow: 0 2px 6px rgba(15, 23, 42, 0.05);
  }
  .metric-section { margin-top: 32px; }
  .metric-section > h2 {
    font-size: 18px;
    margin: 0 0 16px;
    padding-bottom: 8px;
    border-bottom: 2px solid #cbd5e1;
    color: #0f172a;
  }
  .metric-card {
    background: #fff;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 20px 24px;
    margin-bottom: 16px;
    box-shadow: 0 1px 3px rgba(15, 23, 42, 0.04);
  }
  .metric-card h3 {
    margin: 0 0 4px;
    font-size: 16px;
    color: #0f172a;
  }
  .metric-card .parent {
    margin: 0 0 12px;
    font-size: 12px;
    color: #64748b;
  }
  .metric-card h4 {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin: 16px 0 4px;
    color: #475569;
  }
  .metric-card .field p,
  .metric-card .inline-cell p {
    margin: 0;
    font-size: 14px;
  }
  .metric-card ul,
  .metric-card ol {
    margin: 4px 0 0;
    padding-left: 20px;
    font-size: 14px;
  }
  .metric-card li { margin: 2px 0; }
  .metric-card .inline-row {
    display: flex;
    gap: 24px;
    margin-top: 6px;
  }
  .metric-card .inline-row .inline-cell { flex: 1; min-width: 0; }
  .metric-card .cautions ul { color: #b45309; }
  footer.app-footer {
    margin-top: 48px;
    padding-top: 16px;
    border-top: 1px solid #e2e8f0;
    text-align: center;
    font-size: 12px;
    color: #94a3b8;
  }
  @media print {
    @page { size: A4; margin: 16mm; }
    body { background: #fff; padding: 0; }
    .metric-card {
      page-break-inside: avoid;
      box-shadow: none;
    }
    header.cover { page-break-after: avoid; }
    img.logic-model { page-break-after: auto; }
    footer.app-footer { page-break-before: avoid; }
  }
`;

export interface GenerateRecipeHtmlOptions {
  recipe: Recipe;
  logicModelImageDataUrl?: string | null;
}

export function generateRecipeHtml({
  recipe,
  logicModelImageDataUrl,
}: GenerateRecipeHtmlOptions): string {
  const t = labels[recipe.locale];

  const grouped: Record<RecipeTargetCardType, Recipe["items"]> = {
    outputs: [],
    "outcomes-short": [],
    "outcomes-intermediate": [],
  };
  for (const item of recipe.items) {
    grouped[item.parentCardType].push(item);
  }

  const generatedAtDisplay = new Date(recipe.generatedAt).toLocaleString(
    recipe.locale === "ja" ? "ja-JP" : "en-US",
    { dateStyle: "long", timeStyle: "short" },
  );

  const safeLogicModelTitle = htmlEscape(recipe.logicModelTitle);

  const image = logicModelImageDataUrl
    ? `<img class="logic-model" src="${htmlEscape(logicModelImageDataUrl)}" alt="${htmlEscape(t.imageAlt)}">`
    : "";

  const sections = SECTION_ORDER.map((type) => renderSection(type, grouped[type], t)).join("");

  return `<!doctype html>
<html lang="${recipe.locale}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${htmlEscape(DOCUMENT_TITLE)}</title>
<style>${CSS}</style>
</head>
<body>
<div class="container">
<header class="cover">
<h1>${htmlEscape(DOCUMENT_TITLE)}</h1>
<p class="meta">${safeLogicModelTitle} · ${htmlEscape(generatedAtDisplay)} · ${htmlEscape(t.metricsCount(recipe.items.length))}</p>
${image}
</header>
<main>
${sections}
</main>
<footer class="app-footer">${htmlEscape(t.poweredBy)}</footer>
</div>
</body>
</html>`;
}

export function downloadRecipeHtml(html: string, filename: string): void {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
